Repository 6BitBusters/6BitBusters.github.io, pull requests merged in 2025-04, with the labels that each got.

#231 Glossario - 227 / 230
  .github/workflows/build.yml
  .github/workflows/pr_build_check.yml
  Docs/PB/Generali Interni/glossario/01_content.tex
  Docs/PB/Generali Interni/glossario/config/changelog_input.tex
  Docs/PB/Generali Interni/glossario/titlepage.tex
Labels: documentation

#241 Piano di qualifica - 213
  .github/workflows/build.yml
  .github/workflows/pr_build_check.yml
  Docs/PB/Generali Esterni/piano_di_qualifica/05_resoconto.tex
  Docs/PB/Generali Esterni/piano_di_qualifica/config/changelog_input.tex
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/AC.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/BV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/CD.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/CV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/ERR-G.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/EV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/EaC.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/EtC.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/GUL.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/MS.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/PV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/RISCHI.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/RSI.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/SV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/titlepage.tex
  Docs/PB/Generali Interni/glossario/config/changelog_input.tex
  Docs/PB/Generali Interni/glossario/main.tex
  Docs/PB/Generali Interni/glossario/titlepage.tex
Labels: documentation

#259 Piano di qualifica - 246
  Docs/PB/Generali Esterni/piano_di_qualifica/config/changelog_input.tex
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/AC.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/BV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/CD.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/CV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/ERR-G.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/EV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/EaC.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/EtC.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/GUL.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/MS.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/PV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/RISCHI.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/RSI.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/SV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/titlepage.tex
Labels: documentation

#255 Specifica tecnica - 234
  .github/workflows/pr_build_check.yml
  .gitignore
  Docs/PB/Generali Esterni/specifica_tecnica/03_architettura_front.tex
  Docs/PB/Generali Esterni/specifica_tecnica/config/changelog_input.tex
  Docs/PB/Generali Esterni/specifica_tecnica/main.tex
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/appstateslice.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/dataslice.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/datasourceslice.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/error.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/filteroptionslice.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/raycastslice.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/store.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/viewoptionslice.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/ui/axes.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/ui/barchart.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/ui/customcanvas.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/ui/envpage.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/ui/options.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/ui/pages.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/ui/ui.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/package.tex
  Docs/PB/Generali Esterni/specifica_tecnica/titlepage.tex
Labels: documentation

#260 Frontend - Creazione struttura
  .github/workflows/pr_frontend_check.yml
  3Dataviz/frontend/.gitignore
  3Dataviz/frontend/README.md
  3Dataviz/frontend/__test__/.gitkeep
  3Dataviz/frontend/eslint.config.js
  3Dataviz/frontend/index.html
  3Dataviz/frontend/package-lock.json
  3Dataviz/frontend/package.json
  3Dataviz/frontend/public/logo-circle.png
  3Dataviz/frontend/src/App.css
  3Dataviz/frontend/src/App.tsx
  3Dataviz/frontend/src/app/.gitkeep
  3Dataviz/frontend/src/assets/react.svg
  3Dataviz/frontend/src/components/.gitkeep
  3Dataviz/frontend/src/features/.gitkeep
  3Dataviz/frontend/src/index.css
  3Dataviz/frontend/src/main.tsx
  3Dataviz/frontend/src/vite-env.d.ts
  3Dataviz/frontend/tsconfig.app.json
  3Dataviz/frontend/tsconfig.json
  3Dataviz/frontend/tsconfig.node.json
  3Dataviz/frontend/vite.config.ts
Labels: code

#252 VI_2025_03_28
  .gitignore
  Docs/PB/Verbali Interni/VI_2025-03-28/config/changelog_input.tex
  Docs/PB/Verbali Interni/VI_2025-03-28/config/tracking_input.tex
  Docs/PB/Verbali Interni/VI_2025-03-28/content.tex
  Docs/PB/Verbali Interni/VI_2025-03-28/main.tex
  Docs/PB/Verbali Interni/VI_2025-03-28/template/changelog.tex
  Docs/PB/Verbali Interni/VI_2025-03-28/template/images/logo-circle.png
  Docs/PB/Verbali Interni/VI_2025-03-28/template/images/logo-inline.png
  Docs/PB/Verbali Interni/VI_2025-03-28/template/package.tex
  Docs/PB/Verbali Interni/VI_2025-03-28/template/tracking.tex
  Docs/PB/Verbali Interni/VI_2025-03-28/titlepage.tex
Labels: documentation

#250 Piano di progetto - 232
  Docs/PB/Generali Esterni/piano_di_progetto/03_pianificazione.tex
  Docs/PB/Generali Esterni/piano_di_progetto/04_preventivo.tex
  Docs/PB/Generali Esterni/piano_di_progetto/05_consuntivo.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/PB_member_cost_plan.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/changelog_input.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/cost_plan_input_10.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/cost_report_plan_input_9.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/member_plan_input_10.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/member_report_plan_input_9.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/remaining_Hours_9.tex
  Docs/PB/Generali Esterni/piano_di_progetto/template/images/gantt10.png
  Docs/PB/Generali Esterni/piano_di_progetto/template/member_and_cost_plan.tex
  Docs/PB/Generali Esterni/piano_di_progetto/titlepage.tex
Labels: documentation

#288 Frontend - 275
  3Dataviz/frontend/__test__/features/Data/DataSlice.test.ts
  3Dataviz/frontend/package-lock.json
  3Dataviz/frontend/package.json
  3Dataviz/frontend/src/app/.gitkeep
  3Dataviz/frontend/src/app/RootReducer.ts
  3Dataviz/frontend/src/features/Data/DataSlice.ts
  3Dataviz/frontend/src/features/Data/RequestHandler.ts
  3Dataviz/frontend/src/features/Data/interfaces/Data.ts
  3Dataviz/frontend/src/features/Data/interfaces/Entry.ts
  3Dataviz/frontend/src/features/Data/types/DataState.ts
  3Dataviz/frontend/src/features/Data/types/Dataset.ts
  3Dataviz/frontend/src/features/Data/types/FilterPayload.ts
  3Dataviz/frontend/src/features/Data/types/Legend.ts
Labels: code

#293 Frontend - 276
  3Dataviz/frontend/__test__/features/AppStatus/AppStatusSlice.test.ts
  3Dataviz/frontend/__test__/features/DataSource/DataSourceSlice.test.ts
  3Dataviz/frontend/src/app/RootReducer.ts
  3Dataviz/frontend/src/features/AppStatus/AppStatusSlice.ts
  3Dataviz/frontend/src/features/DataSource/DataSourceSlice.ts
  3Dataviz/frontend/src/features/DataSource/RequestHandler.ts
  3Dataviz/frontend/src/features/DataSource/types/DataSourceState.ts
  3Dataviz/frontend/src/features/DataSource/types/DatasetInfo.ts
Labels: code

#258 VE_2025_04_02
  Docs/PB/Verbali Esterni/VE_2025-04-02/VE_2025-04-02_firmato.pdf
  Docs/PB/Verbali Esterni/VE_2025-04-02/config/changelog_input.tex
  Docs/PB/Verbali Esterni/VE_2025-04-02/config/tracking_input.tex
  Docs/PB/Verbali Esterni/VE_2025-04-02/content_01.tex
  Docs/PB/Verbali Esterni/VE_2025-04-02/main.tex
  Docs/PB/Verbali Esterni/VE_2025-04-02/template/changelog.tex
  Docs/PB/Verbali Esterni/VE_2025-04-02/template/images/logo-circle.png
  Docs/PB/Verbali Esterni/VE_2025-04-02/template/images/logo-inline.png
  Docs/PB/Verbali Esterni/VE_2025-04-02/template/package.tex
  Docs/PB/Verbali Esterni/VE_2025-04-02/template/tracking.tex
  Docs/PB/Verbali Esterni/VE_2025-04-02/titlepage.tex
Labels: documentation

#291 Code/backend 285
  .github/workflows/pr_backend_check.yml
  3Dataviz/backend/.prettierrc
  3Dataviz/backend/docker-compose.yml
  3Dataviz/backend/eslint.config.mjs
  3Dataviz/backend/package-lock.json
  3Dataviz/backend/package.json
  3Dataviz/backend/src/app.controller.spec.ts
  3Dataviz/backend/src/app.controller.ts
  3Dataviz/backend/src/app.module.ts
  3Dataviz/backend/src/app.service.ts
  3Dataviz/backend/src/exceptions/too-many-requests.exception.ts
  3Dataviz/backend/src/modules/cache/services/cache.service.spec.ts
  3Dataviz/backend/src/modules/cache/services/cache.service.ts
  3Dataviz/backend/src/modules/data-source/controllers/data-source.controller.spec.ts
  3Dataviz/backend/src/modules/data-source/data-source.module.ts
  3Dataviz/backend/src/modules/data-visualization/controllers/data-visualization.controller.spec.ts
  3Dataviz/backend/src/modules/data-visualization/data-visualization.module.ts
  3Dataviz/backend/src/modules/data-visualization/services/data-visualization.service.spec.ts
  3Dataviz/backend/src/modules/data-visualization/services/data-visualization.service.ts
  3Dataviz/backend/src/modules/fetchers/config.ts
  3Dataviz/backend/src/modules/fetchers/factories/fetchers.factory.spec.ts
  3Dataviz/backend/src/modules/fetchers/factories/fetchers.factory.ts
  3Dataviz/backend/src/modules/fetchers/fetchers.module.ts
  3Dataviz/backend/src/modules/fetchers/services/currency-api-fetcher.spec.ts
  3Dataviz/backend/src/modules/fetchers/services/currency-api-fetcher.ts
  3Dataviz/backend/src/modules/fetchers/services/flights-api-fetcher.spec.ts
  3Dataviz/backend/src/modules/fetchers/services/flights-api-fetcher.ts
  3Dataviz/backend/src/modules/fetchers/services/population-api-fetcher.ts
  3Dataviz/backend/src/modules/fetchers/services/weather-api-fetcher.spec.ts
  3Dataviz/backend/test/data-source.e2e-spec.ts
  3Dataviz/backend/test/data-visualization.e2e-spec.ts
  3Dataviz/backend/tsconfig.build.json
Labels: code

#297 Norme di progetto - 247
  Docs/PB/Generali Interni/norme_di_progetto/03_processi_supporto.tex
  Docs/PB/Generali Interni/norme_di_progetto/config/changelog_input.tex
  Docs/PB/Generali Interni/norme_di_progetto/titlepage.tex
Labels: documentation

#299 Frontend - 282
  3Dataviz/frontend/__test__/features/Raycast/RaycastHitSlice.test.ts
  3Dataviz/frontend/src/app/RootReducer.ts
  3Dataviz/frontend/src/features/Raycast/RaycastHitSlice.ts
  3Dataviz/frontend/src/features/Raycast/types/RaycastHit.ts
Labels: code

#314 Frontend - 309
  3Dataviz/frontend/__test__/features/AppStatus/AppStatusSlice.test.ts
  3Dataviz/frontend/__test__/features/Data/DataSlice.test.ts
  3Dataviz/frontend/__test__/features/DataSource/DataSourceSlice.test.ts
  3Dataviz/frontend/__test__/features/Raycast/RaycastHitSlice.test.ts
  3Dataviz/frontend/__test__/utils/StateMockCreator.ts
  3Dataviz/frontend/package.json
  3Dataviz/frontend/src/app/RootReducer.ts
  3Dataviz/frontend/src/features/AppStatus/AppSlice.ts
  3Dataviz/frontend/src/features/Data/DataSlice.ts
  3Dataviz/frontend/src/features/DataSource/DataSourceSlice.ts
  3Dataviz/frontend/src/features/Raycast/RaycastHitSlice.ts
  3Dataviz/frontend/src/features/Raycast/types/RaycastHit.ts
  3Dataviz/frontend/src/features/Raycast/types/RaycastHitState.ts
Labels: enhancement, code

#289 Specifica Tecnica - 235
  Docs/PB/Generali Esterni/specifica_tecnica/04_architettura_back.tex
  Docs/PB/Generali Esterni/specifica_tecnica/config/changelog_input.tex
  Docs/PB/Generali Esterni/specifica_tecnica/main.tex
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/CacheModule.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/DataSourceModule.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/DataVisualizationModule.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/Strategy.png
  Docs/PB/Generali Esterni/specifica_tecnica/titlepage.tex
Labels: documentation

#317 Specifica - 308
  Docs/PB/Generali Esterni/specifica_tecnica/02_tecnologie.tex
  Docs/PB/Generali Esterni/specifica_tecnica/03_architettura_front.tex
  Docs/PB/Generali Esterni/specifica_tecnica/04_architettura_back.tex
  Docs/PB/Generali Esterni/specifica_tecnica/config/changelog_input.tex
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_back/CacheModule.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_back/DataSourceModule.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_back/DataVisualizationModule.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_back/Strategy.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/AppSlice.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/CustomError.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/RaycastHitSlice.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/appstateslice.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/dataslice.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/datasourceslice.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/error.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/filteroptionslice.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/raycastslice.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/store.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/logic/viewoptionslice.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/ui/EnvironmentPage.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/ui/axes.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/ui/barchart.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/ui/customcanvas.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/ui/envpage.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/ui/homepage.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/ui/options.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/ui/pages.png
  Docs/PB/Generali Esterni/specifica_tecnica/template/images/uml_front/ui/ui.png
  Docs/PB/Generali Esterni/specifica_tecnica/titlepage.tex
Labels: documentation

#320 Glossario - 318
  .gitignore
  Docs/PB/Generali Interni/glossario/01_content.tex
  Docs/PB/Generali Interni/glossario/config/changelog_input.tex
  Docs/PB/Generali Interni/glossario/titlepage.tex
Labels: documentation

#312 VE_2025-04-16-311
  Docs/PB/Verbali Esterni/VE_2025-04-16/config/changelog_input.tex
  Docs/PB/Verbali Esterni/VE_2025-04-16/config/tracking_input.tex
  Docs/PB/Verbali Esterni/VE_2025-04-16/content_01.tex
  Docs/PB/Verbali Esterni/VE_2025-04-16/main.tex
  Docs/PB/Verbali Esterni/VE_2025-04-16/template/changelog.tex
  Docs/PB/Verbali Esterni/VE_2025-04-16/template/images/logo-circle.png
  Docs/PB/Verbali Esterni/VE_2025-04-16/template/images/logo-inline.png
  Docs/PB/Verbali Esterni/VE_2025-04-16/template/package.tex
  Docs/PB/Verbali Esterni/VE_2025-04-16/template/tracking.tex
  Docs/PB/Verbali Esterni/VE_2025-04-16/titlepage.tex
Labels: documentation

#333 Analisi dei requisiti - 236
  Docs/PB/Generali Esterni/analisi_dei_requisiti/02_use_cases.tex
  Docs/PB/Generali Esterni/analisi_dei_requisiti/03_requisiti.tex
  Docs/PB/Generali Esterni/analisi_dei_requisiti/config/changelog_input.tex
  Docs/PB/Generali Esterni/analisi_dei_requisiti/template/images/UC19.png
  Docs/PB/Generali Esterni/analisi_dei_requisiti/template/images/UC3.png
  Docs/PB/Generali Esterni/analisi_dei_requisiti/template/requirements.tex
  Docs/PB/Generali Esterni/analisi_dei_requisiti/titlepage.tex
Labels: documentation

#335 Frontend - 268
  3Dataviz/frontend/__test__/components/ApiSelector/ApiSelector.test.tsx
  3Dataviz/frontend/__test__/features/AppStatus/AppStatusSlice.test.ts
  3Dataviz/frontend/__test__/features/DataSource/DataSourceSlice.test.ts
  3Dataviz/frontend/__test__/pages/EnvironmentPage/EnvironmentPage.test.tsx
  3Dataviz/frontend/__test__/pages/ErrorPage/ErrorPage.test.tsx
  3Dataviz/frontend/__test__/pages/HomePage/HomePage.test.tsx
  3Dataviz/frontend/package-lock.json
  3Dataviz/frontend/package.json
  3Dataviz/frontend/src/App.css
  3Dataviz/frontend/src/App.tsx
  3Dataviz/frontend/src/components/.gitkeep
  3Dataviz/frontend/src/components/apiSelector/apiSelector.css
  3Dataviz/frontend/src/components/apiSelector/apiSelector.tsx
  3Dataviz/frontend/src/components/datasetItem/datasetItem.css
  3Dataviz/frontend/src/components/datasetItem/datasetItem.tsx
  3Dataviz/frontend/src/components/footer/footer.css
  3Dataviz/frontend/src/components/footer/footer.tsx
  3Dataviz/frontend/src/features/AppStatus/AppSlice.ts
  3Dataviz/frontend/src/features/AppStatus/Utils/ErrorSerializer.ts
  3Dataviz/frontend/src/features/AppStatus/types/AppState.ts
  3Dataviz/frontend/src/features/Data/RequestHandler.ts
  3Dataviz/frontend/src/features/DataSource/RequestHandler.ts
  3Dataviz/frontend/src/index.css
  3Dataviz/frontend/src/main.tsx
  3Dataviz/frontend/src/pages/environmentPage/environmentPage.css
  3Dataviz/frontend/src/pages/environmentPage/environmentPage.tsx
  3Dataviz/frontend/src/pages/errorPage/errorPage.css
  3Dataviz/frontend/src/pages/errorPage/errorPage.tsx
  3Dataviz/frontend/src/pages/homePage/homePage.css
  3Dataviz/frontend/src/pages/homePage/homePage.tsx
  3Dataviz/frontend/vitest.setup.ts
Labels: code

#331 Manuale utente - 322
  .gitignore
  Docs/PB/Generali Esterni/manuale_utente/01_content.tex
  Docs/PB/Generali Esterni/manuale_utente/01_intro.tex
  Docs/PB/Generali Esterni/manuale_utente/02_panoramica.tex
  Docs/PB/Generali Esterni/manuale_utente/03_interfaccia.tex
  Docs/PB/Generali Esterni/manuale_utente/04_funzionalita.tex
  Docs/PB/Generali Esterni/manuale_utente/05_glossario.tex
  Docs/PB/Generali Esterni/manuale_utente/config/changelog_input.tex
  Docs/PB/Generali Esterni/manuale_utente/main.tex
  Docs/PB/Generali Esterni/manuale_utente/template/images/3Dinteractions.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/avgplane.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/comandi.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/env3D.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/envpage.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/gizmo.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/homepage.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/options.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/optionsexpandbtn.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/resetcam.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/selected.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/table.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/tableexpandbtn.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/tooltip.png
  Docs/PB/Generali Esterni/manuale_utente/titlepage.tex
Labels: documentation

#340 Manuale utente - 321
  Docs/PB/Generali Esterni/manuale_utente/02_panoramica.tex
  Docs/PB/Generali Esterni/manuale_utente/03_interfaccia.tex
  Docs/PB/Generali Esterni/manuale_utente/04_funzionalita.tex
  Docs/PB/Generali Esterni/manuale_utente/config/changelog_input.tex
  Docs/PB/Generali Esterni/manuale_utente/template/images/env/autofocus.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/env/current.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/env/envpage.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/env/legend.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/env/options.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/env/plane.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/env/table.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/home/btn.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/home/dataset.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/home/homepage.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/home/options.png
  Docs/PB/Generali Esterni/manuale_utente/template/images/home/select.png
  Docs/PB/Generali Esterni/manuale_utente/titlepage.tex
Labels: documentation

#358 Bug report - hotfix
  Docs/PB/Generali Esterni/bug_report/titlepage.tex
Labels: documentation, correction

#359 VI_2025-04-14 - hotfix
  Docs/PB/Verbali Interni/VI_2025-04-14/config/changelog_input.tex
Labels: documentation, correction

#357 VI_2025-04-26 - 353
  Docs/PB/Verbali Interni/VI_2025-04-26/config/changelog_input.tex
  Docs/PB/Verbali Interni/VI_2025-04-26/config/tracking_input.tex
  Docs/PB/Verbali Interni/VI_2025-04-26/content.tex
  Docs/PB/Verbali Interni/VI_2025-04-26/main.tex
  Docs/PB/Verbali Interni/VI_2025-04-26/template/changelog.tex
  Docs/PB/Verbali Interni/VI_2025-04-26/template/images/logo-circle.png
  Docs/PB/Verbali Interni/VI_2025-04-26/template/images/logo-inline.png
  Docs/PB/Verbali Interni/VI_2025-04-26/template/package.tex
  Docs/PB/Verbali Interni/VI_2025-04-26/template/tracking.tex
  Docs/PB/Verbali Interni/VI_2025-04-26/titlepage.tex
Labels: documentation

#352 Specifica - 341
  Docs/PB/Generali Esterni/specifica_tecnica/05_architettura_deploy.tex
  Docs/PB/Generali Esterni/specifica_tecnica/config/changelog_input.tex
  Docs/PB/Generali Esterni/specifica_tecnica/main.tex
  Docs/PB/Generali Esterni/specifica_tecnica/titlepage.tex
Labels: documentation

#345 Norme di progetto - 343
  .gitignore
  Docs/PB/Generali Interni/norme_di_progetto/02_processi_primari.tex
  Docs/PB/Generali Interni/norme_di_progetto/config/changelog_input.tex
  Docs/PB/Generali Interni/norme_di_progetto/titlepage.tex
Labels: documentation
