Repository 6BitBusters/6BitBusters.github.io, pull requests merged in 2025-05, with the labels that each got.

#360 Piano di progetto-344
  .gitignore
  Docs/PB/Generali Esterni/piano_di_progetto/03_pianificazione.tex
  Docs/PB/Generali Esterni/piano_di_progetto/04_preventivo.tex
  Docs/PB/Generali Esterni/piano_di_progetto/05_consuntivo.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/RTB_cost_table.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/RTB_member_table.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/changelog_input.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/cost_plan_input_11.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/cost_plan_input_12.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/cost_report_plan_input_10.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/cost_report_plan_input_11.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/cost_report_plan_input_4.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/cost_report_plan_input_9.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/member_plan_input_11.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/member_plan_input_12.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/member_report_plan_input_10.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/member_report_plan_input_11.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/member_report_plan_input_4.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/member_report_plan_input_9.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/remaining_Hours_10.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/remaining_Hours_11.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/remaining_Hours_9.tex
  Docs/PB/Generali Esterni/piano_di_progetto/template/images/gantt11.png
  Docs/PB/Generali Esterni/piano_di_progetto/template/images/gantt12.png
  Docs/PB/Generali Esterni/piano_di_progetto/titlepage.tex
Labels: documentation

#371 Frontend - radio button
  3Dataviz/frontend/src/components/UI/options/options.css
  3Dataviz/frontend/src/components/UI/ui.css
Labels: code

#374 Hotfix - Piano di progetto
  Docs/PB/Generali Esterni/piano_di_progetto/05_consuntivo.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/PB_cost_table.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/PB_member_table.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/TOTAL_cost_table.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/TOTAL_member_table.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/cost_report_plan_input_11.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/member_report_plan_input_11.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/remaining_Hours_11.tex
  Docs/PB/Generali Esterni/piano_di_progetto/config/remaining_Hours_12.tex
Labels: correction

#372 Piano di qualifica - 342
  Docs/PB/Generali Esterni/piano_di_qualifica/04_test.tex
  Docs/PB/Generali Esterni/piano_di_qualifica/05_resoconto.tex
  Docs/PB/Generali Esterni/piano_di_qualifica/config/changelog_input.tex
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/AC.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/BV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/CC.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/CD.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/CV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/DC.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/DE.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/ERR-G.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/EV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/EaC.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/EtC.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/GUL.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/LINEE-F.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/LINEE-M.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/MS.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/PM.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/PV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/REQ-D.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/REQ-O.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/REQ-OP.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/RISCHI.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/RSI.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/SB.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/SV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/TEMP-A.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/TEMP-C.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/TEMP-R.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/TEST.png
  Docs/PB/Generali Esterni/piano_di_qualifica/titlepage.tex
Labels: documentation

#381 Hotfix- piano di qualifica
  Docs/PB/Generali Esterni/piano_di_qualifica/05_resoconto.tex
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/B-COV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/C-COV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/DC.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/REQ-D.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/REQ-O.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/REQ-OP.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/S-COV.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/SB.png
  Docs/PB/Generali Esterni/piano_di_qualifica/template/images/TEST.png
Labels: enhancement
